actions: imporve semver tagging

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -13,7 +13,7 @@ jobs:
     runs-on: ubuntu-24.04
     steps:
       - name: Checkout
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6.0.1
         with:
           fetch-depth: 0
 
@@ -25,7 +25,7 @@ jobs:
 
       - name: Generate metadata
         id: meta
-        uses: docker/metadata-action@v5
+        uses: docker/metadata-action@v5.10.0
         with:
           images: |
             inspirehep/hep
@@ -36,11 +36,14 @@ jobs:
           tags: "type=sha"
 
       - name: Login to Harbor
-        uses: docker/login-action@v2
+        uses: docker/login-action@v3.6.0
         with:
           registry: "registry.cern.ch"
           username: ${{ secrets.HARBOR_USERNAME }}
           password: ${{ secrets.HARBOR_PASSWORD }}
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3.11.1
 
       - name: push semver tag
         env:
@@ -57,13 +60,14 @@ jobs:
             SHA_TAG="${tag##*:}"
 
             if [[ ! "$IMAGE" =~ ^registry\.cern\.ch/cern-sis/inspire/ ]]; then
-              continue
+                continue
             fi
 
             echo "Processing $IMAGE:$SHA_TAG --> $IMAGE:$RELEASE_TAG"
-            docker pull "$IMAGE:$SHA_TAG"
-            docker tag "$IMAGE:$SHA_TAG" "$IMAGE:$RELEASE_TAG"
-            docker push "$IMAGE:$RELEASE_TAG"
+            if ! docker buildx imagetools create "$IMAGE:$SHA_TAG" --tag "$IMAGE:$RELEASE_TAG"; then
+                echo "Error: Failed to retag image"
+                exit 1
+            fi
           done
 
       - name: send event inspire
@@ -80,3 +84,5 @@ jobs:
           event-type: release
           images: ${{ env.DOCKER_METADATA_OUTPUT_TAGS }}
           token: ${{ secrets.PAT_FIRE_EVENTS_ON_CERN_SIS_KUBERNETES }}
+
+
